// Builds migration/seed.sql from the Supabase export + a fresh products fetch
// (the fetch captures the one product whose image_url is a large base64 data URL).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dir = dirname(fileURLToPath(import.meta.url));
const exportData = JSON.parse(readFileSync(join(__dir, "supabase-export.json"), "utf8"));

const SUPABASE_URL = "https://sxsinmsriusxbrhcjtpk.supabase.co";
const ANON =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4c2lubXNyaXVzeGJyaGNqdHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0NDI2NTMsImV4cCI6MjA5NTAxODY1M30.b9Qn3cqTwK-52Jcy08tQFjk3BsAWPc1AMYJSgokP0Wc";

const q = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  return "'" + String(v).replace(/'/g, "''") + "'";
};

function insert(table, cols, rows) {
  if (!rows.length) return "";
  const colList = cols.join(", ");
  const values = rows.map((r) => "(" + cols.map((c) => q(r[c])).join(", ") + ")").join(",\n  ");
  return `INSERT INTO ${table} (${colList}) VALUES\n  ${values};\n\n`;
}

const products = await fetch(`${SUPABASE_URL}/rest/v1/products?select=*`, {
  headers: { apikey: ANON, Authorization: `Bearer ${ANON}` },
}).then((r) => r.json());

if (!Array.isArray(products)) throw new Error("Failed to fetch products: " + JSON.stringify(products));

let sql = "-- Generated by build-seed.mjs. Idempotent-ish: clears app tables first.\n";
sql += "DELETE FROM orders;\nDELETE FROM products;\nDELETE FROM categories;\nDELETE FROM store_settings;\n\n";

sql += insert("categories", ["id", "name", "slug", "created_at"], exportData.categories);
sql += insert(
  "products",
  ["id", "title", "description", "price", "sale_price", "category_id", "stock", "status", "image_url", "badge", "rating", "created_at", "updated_at"],
  products,
);
sql += insert(
  "orders",
  ["id", "user_id", "items", "status", "total", "created_at"],
  exportData.orders.map((o) => ({ ...o, items: JSON.stringify(o.items) })),
);
sql += insert(
  "store_settings",
  ["id", "banner_text", "global_discount_pct", "free_shipping_threshold", "updated_at"],
  exportData.store_settings,
);

writeFileSync(join(__dir, "seed.sql"), sql);
console.log(`Wrote seed.sql: ${exportData.categories.length} categories, ${products.length} products, ${exportData.orders.length} orders, ${exportData.store_settings.length} settings`);
