/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as WagyuRouteImport } from './routes/wagyu'
import { Route as StoreIndexRouteImport } from './routes/_store/index'
import { Route as StoreAboutRouteImport } from './routes/_store/about'
import { Route as StoreAccountRouteImport } from './routes/_store/account'
import { Route as StoreAddressesRouteImport } from './routes/_store/addresses'
import { Route as StoreCheckoutRouteImport } from './routes/_store/checkout'
import { Route as StoreFaqRouteImport } from './routes/_store/faq'
import { Route as StoreOffersRouteImport } from './routes/_store/offers'
import { Route as StoreOrdersRouteImport } from './routes/_store/orders'
import { Route as StorePrivacyRouteImport } from './routes/_store/privacy'
import { Route as StoreRefundPolicyRouteImport } from './routes/_store/refund-policy'
import { Route as StoreShippingPolicyRouteImport } from './routes/_store/shipping-policy'
import { Route as StoreShopRouteImport } from './routes/_store/shop'
import { Route as StoreThankYouRouteImport } from './routes/_store/thank-you'
import { Route as StoreWishlistRouteImport } from './routes/_store/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCollectionsRouteImport } from './routes/admin/collections'
import { Route as AdminMainNavigatorRouteImport } from './routes/admin/main-navigator'
import { Route as AdminMarketingRouteImport } from './routes/admin/marketing'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminRestoreRouteImport } from './routes/admin/restore'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTranslationsRouteImport } from './routes/admin/translations'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as StoreCollectionsSlugRouteImport } from './routes/_store/collections.$slug'
import { Route as StorePayIdRouteImport } from './routes/_store/pay.$id'
import { Route as StoreProductIdRouteImport } from './routes/_store/product.$id'

const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WagyuRoute = WagyuRouteImport.update({
  id: '/wagyu',
  path: '/wagyu',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAboutRoute = StoreAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAccountRoute = StoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAddressesRoute = StoreAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreFaqRoute = StoreFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOffersRoute = StoreOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOrdersRoute = StoreOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StoreRoute,
} as any)
const StorePrivacyRoute = StorePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRefundPolicyRoute = StoreRefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => StoreRoute,
} as any)
const StoreShippingPolicyRoute = StoreShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => StoreRoute,
} as any)
const StoreShopRoute = StoreShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StoreRoute,
} as any)
const StoreThankYouRoute = StoreThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => StoreRoute,
} as any)
const StoreWishlistRoute = StoreWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => StoreRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMainNavigatorRoute = AdminMainNavigatorRouteImport.update({
  id: '/main-navigator',
  path: '/main-navigator',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestoreRoute = AdminRestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const StoreCollectionsSlugRoute = StoreCollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StorePayIdRoute = StorePayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProductIdRoute = StoreProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/wagyu': typeof WagyuRoute
  '/about': typeof StoreAboutRoute
  '/account': typeof StoreAccountRoute
  '/addresses': typeof StoreAddressesRoute
  '/checkout': typeof StoreCheckoutRoute
  '/faq': typeof StoreFaqRoute
  '/offers': typeof StoreOffersRoute
  '/orders': typeof StoreOrdersRoute
  '/privacy': typeof StorePrivacyRoute
  '/refund-policy': typeof StoreRefundPolicyRoute
  '/shipping-policy': typeof StoreShippingPolicyRoute
  '/shop': typeof StoreShopRoute
  '/thank-you': typeof StoreThankYouRoute
  '/wishlist': typeof StoreWishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/main-navigator': typeof AdminMainNavigatorRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/restore': typeof AdminRestoreRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/$slug': typeof StoreCollectionsSlugRoute
  '/pay/$id': typeof StorePayIdRoute
  '/product/$id': typeof StoreProductIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/wagyu': typeof WagyuRoute
  '/about': typeof StoreAboutRoute
  '/account': typeof StoreAccountRoute
  '/addresses': typeof StoreAddressesRoute
  '/checkout': typeof StoreCheckoutRoute
  '/faq': typeof StoreFaqRoute
  '/offers': typeof StoreOffersRoute
  '/orders': typeof StoreOrdersRoute
  '/privacy': typeof StorePrivacyRoute
  '/refund-policy': typeof StoreRefundPolicyRoute
  '/shipping-policy': typeof StoreShippingPolicyRoute
  '/shop': typeof StoreShopRoute
  '/thank-you': typeof StoreThankYouRoute
  '/wishlist': typeof StoreWishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/main-navigator': typeof AdminMainNavigatorRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/restore': typeof AdminRestoreRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminIndexRoute
  '/collections/$slug': typeof StoreCollectionsSlugRoute
  '/pay/$id': typeof StorePayIdRoute
  '/product/$id': typeof StoreProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/wagyu': typeof WagyuRoute
  '/_store/about': typeof StoreAboutRoute
  '/_store/account': typeof StoreAccountRoute
  '/_store/addresses': typeof StoreAddressesRoute
  '/_store/checkout': typeof StoreCheckoutRoute
  '/_store/faq': typeof StoreFaqRoute
  '/_store/offers': typeof StoreOffersRoute
  '/_store/orders': typeof StoreOrdersRoute
  '/_store/privacy': typeof StorePrivacyRoute
  '/_store/refund-policy': typeof StoreRefundPolicyRoute
  '/_store/shipping-policy': typeof StoreShippingPolicyRoute
  '/_store/shop': typeof StoreShopRoute
  '/_store/thank-you': typeof StoreThankYouRoute
  '/_store/wishlist': typeof StoreWishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/main-navigator': typeof AdminMainNavigatorRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/restore': typeof AdminRestoreRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/_store/': typeof StoreIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_store/collections/$slug': typeof StoreCollectionsSlugRoute
  '/_store/pay/$id': typeof StorePayIdRoute
  '/_store/product/$id': typeof StoreProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/wagyu'
    | '/about'
    | '/account'
    | '/addresses'
    | '/checkout'
    | '/faq'
    | '/offers'
    | '/orders'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/shop'
    | '/thank-you'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/main-navigator'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/restore'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/users'
    | '/admin/'
    | '/collections/$slug'
    | '/pay/$id'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/wagyu'
    | '/about'
    | '/account'
    | '/addresses'
    | '/checkout'
    | '/faq'
    | '/offers'
    | '/orders'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/shop'
    | '/thank-you'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/main-navigator'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/restore'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/collections/$slug'
    | '/pay/$id'
    | '/product/$id'
  id:
    | '__root__'
    | '/_store'
    | '/admin'
    | '/auth'
    | '/wagyu'
    | '/_store/about'
    | '/_store/account'
    | '/_store/addresses'
    | '/_store/checkout'
    | '/_store/faq'
    | '/_store/offers'
    | '/_store/orders'
    | '/_store/privacy'
    | '/_store/refund-policy'
    | '/_store/shipping-policy'
    | '/_store/shop'
    | '/_store/thank-you'
    | '/_store/wishlist'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/main-navigator'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/restore'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/users'
    | '/_store/'
    | '/admin/'
    | '/_store/collections/$slug'
    | '/_store/pay/$id'
    | '/_store/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  WagyuRoute: typeof WagyuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wagyu': {
      id: '/wagyu'
      path: '/wagyu'
      fullPath: '/wagyu'
      preLoaderRoute: typeof WagyuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/about': {
      id: '/_store/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StoreAboutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/account': {
      id: '/_store/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof StoreAccountRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/addresses': {
      id: '/_store/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof StoreAddressesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout': {
      id: '/_store/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/faq': {
      id: '/_store/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof StoreFaqRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/offers': {
      id: '/_store/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof StoreOffersRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/orders': {
      id: '/_store/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof StoreOrdersRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/privacy': {
      id: '/_store/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof StorePrivacyRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/refund-policy': {
      id: '/_store/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof StoreRefundPolicyRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/shipping-policy': {
      id: '/_store/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof StoreShippingPolicyRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/shop': {
      id: '/_store/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof StoreShopRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/thank-you': {
      id: '/_store/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof StoreThankYouRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/wishlist': {
      id: '/_store/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof StoreWishlistRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/main-navigator': {
      id: '/admin/main-navigator'
      path: '/main-navigator'
      fullPath: '/admin/main-navigator'
      preLoaderRoute: typeof AdminMainNavigatorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restore': {
      id: '/admin/restore'
      path: '/restore'
      fullPath: '/admin/restore'
      preLoaderRoute: typeof AdminRestoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/collections/$slug': {
      id: '/_store/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof StoreCollectionsSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/pay/$id': {
      id: '/_store/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof StorePayIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/product/$id': {
      id: '/_store/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof StoreProductIdRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface StoreRouteChildren {
  StoreAboutRoute: typeof StoreAboutRoute
  StoreAccountRoute: typeof StoreAccountRoute
  StoreAddressesRoute: typeof StoreAddressesRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreFaqRoute: typeof StoreFaqRoute
  StoreOffersRoute: typeof StoreOffersRoute
  StoreOrdersRoute: typeof StoreOrdersRoute
  StorePrivacyRoute: typeof StorePrivacyRoute
  StoreRefundPolicyRoute: typeof StoreRefundPolicyRoute
  StoreShippingPolicyRoute: typeof StoreShippingPolicyRoute
  StoreShopRoute: typeof StoreShopRoute
  StoreThankYouRoute: typeof StoreThankYouRoute
  StoreWishlistRoute: typeof StoreWishlistRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreCollectionsSlugRoute: typeof StoreCollectionsSlugRoute
  StorePayIdRoute: typeof StorePayIdRoute
  StoreProductIdRoute: typeof StoreProductIdRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAboutRoute: StoreAboutRoute,
  StoreAccountRoute: StoreAccountRoute,
  StoreAddressesRoute: StoreAddressesRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreFaqRoute: StoreFaqRoute,
  StoreOffersRoute: StoreOffersRoute,
  StoreOrdersRoute: StoreOrdersRoute,
  StorePrivacyRoute: StorePrivacyRoute,
  StoreRefundPolicyRoute: StoreRefundPolicyRoute,
  StoreShippingPolicyRoute: StoreShippingPolicyRoute,
  StoreShopRoute: StoreShopRoute,
  StoreThankYouRoute: StoreThankYouRoute,
  StoreWishlistRoute: StoreWishlistRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreCollectionsSlugRoute: StoreCollectionsSlugRoute,
  StorePayIdRoute: StorePayIdRoute,
  StoreProductIdRoute: StoreProductIdRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminMainNavigatorRoute: typeof AdminMainNavigatorRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRestoreRoute: typeof AdminRestoreRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminMainNavigatorRoute: AdminMainNavigatorRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRestoreRoute: AdminRestoreRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTranslationsRoute: AdminTranslationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  WagyuRoute: WagyuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
